# Generated by Django 5.1.7 on 2025-06-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_available',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('occupied', 'Occupied')], default='available', max_length=10),
        ),
    ]
